metrics:
  reporters:
    - type: graphite
      host: ${GRAPHITE_PORT_2003_TCP_ADDR} # must be provided by docker link
      port: 2003
      frequency: 10 seconds
    - type: ganglia
      host: ${GANGLIA_PORT_8649_UDP_ADDR} # must be provided by docker link
      port: 8649
    - type: statsd
      host: ${GRAPHITE_PORT_8125_UDP_ADDR} # must be provided by docker link
      port: 8125
